local lsp_zero = require('lsp-zero')
local telescope = require('telescope.builtin')

lsp_zero.on_attach(function(client, bufnr)
    -- see :help lsp-zero-keybindings
    -- to learn the available actions
    local opts = { buffer = bufnr, remap = false }
    vim.keymap.set('n', '<leader>=', function()
        vim.lsp.buf.format()
    end, opts)
    vim.keymap.set('n', '<leader>r', function()
        vim.lsp.buf.rename()
    end, opts)
    vim.keymap.set('n', 'K', function()
        vim.lsp.buf.hover()
    end, opts)
    vim.keymap.set('n', 'gd', function()
        vim.lsp.buf.definition()
    end, opts)
    vim.keymap.set('n', 'gD', function()
        vim.lsp.buf.declaration()
    end, opts)
    vim.keymap.set('n', 'gi', function()
        telescope.lsp_definitions()
    end, opts)
    vim.keymap.set('n', 'go', function()
        telescope.lsp_type_definitions()
    end, opts)
    vim.keymap.set('n', 'gr', function()
        telescope.lsp_references()
    end, opts)
    vim.keymap.set('n', 'gs', function()
        vim.lsp.buf.signature_help()
    end, opts)
    vim.keymap.set('n', '<leader>ca', function()
        vim.lsp.buf.code_action()
    end, opts)
    vim.keymap.set('n', 'gl', function()
        vim.diagnostic.open_float()
    end, opts)
    vim.keymap.set('n', '[d', function()
        vim.diagnostic.goto_prev()
    end, opts)
    vim.keymap.set('n', ']d', function()
        vim.diagnostic.goto_next()
    end, opts)
end)

require('mason').setup({})
require('mason-lspconfig').setup({
    ensure_installed = {},
    handlers = {
        lsp_zero.default_setup,
    },
})
